### ISSUE TITLE
ts source missing?

### ISSUE THREAD

**Issue by artifacts** [ievgennaida/animation-timeline-control#4]
Hi Ievgen,

thanks for sharing your project!

#### I'd like to send a PR with a minor change:

`window.requestAnimationFrame.call(this, redrawInternal);
`

I embedded the timeline into a vue app and the above call raises an Illegal invocation error when calling redraw from a watcher: _this_ is then the timeline object,  not the window.
It works after changing it to 

`window.requestAnimationFrame(redrawInternal);`

Is there another reason for the original call that I am missing here?

#### Typescript sources:

Did you exclude the typescript sources on purpose? Contributing to your project would be easier with the .ts files.

Thanks,
Michael

**Comment by ievgennaida** [comment]
Hello, 
Sorry for the inconvenience of your VUE project. 
I have tested It only from angular and from the HTML page and it was fine.
I see no reason to bind **window.requestAnimationFrame.call** might be there for the historical reasons. and can be removed. 

Initially, component supposed to be very small, so pure javascript was used. 
Now I am only planning to migrate to typescript due to typos and bugs. 
Nevertheless, definitions are here
https://github.com/ievgennaida/js-animation-timeline-control/blob/master/index.d.ts

**Comment by ievgennaida** [comment]
@artifacts There is a chance that I will migrate to TypeScript this week, but please be aware that it will be a braking change while I dislike some APIs and it will contain some fixes that are hanging for a while.

**Comment by artifacts** [comment]
@ievgennaida Ok, great. I'll send you some more pull requests anyway today. I broke up my changes into small parts so you can pick what you like.

**Comment by ievgennaida** [comment]
2.0.7 is published
